variable "sns_topic_name" {
  type    = "string"
  default = "The friendly name for the SNS topic. By default generated by Terraform"
}

variable "sqs_queue_name" {
  type    = "string"
  default = ""
}
